---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
  labels:
    type: "boot-app"
  name: "petclinic"
spec:
  ports:
  - name: "web"
    port: 8080
    targetPort: 8080
  selector:
    type: "boot-app"
  type: NodePort
